apiVersion: apps/v1
kind: Deployment
metadata:
  name: alchemist-pull-deployment
  labels:
    app: alchemist-pull-processor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-alchemist-processor
  template:
    metadata:
      annotations:
        iam.amazonaws.com/role: deafrica-ec2-s3_access
      labels:
        app: python-alchemist-processor
    spec:
      nodeSelector:
        beta.kubernetes.io/os: linux
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: nodetype
                    operator: In
                    values:
                      - spot
      containers:
      - name: alchemist-processor-container
        image: opendatacube/datacube-alchemist
        command: [ "datacube-alchemist", "pullfromqueue" ]
        resources:
          requests:
            cpu: 1
            memory: 8192Mi
          limits:
            memory: 8192Mi
        tty: true
        stdin: true
        env:
        - name: ALCHEMIST_PULLFROMQUEUE_MESSAGE_QUEUE
          value: "alchemist-standard"
        - name: AWS_DEFAULT_REGION
          value: us-west-2
        - name: DATACUBE_CONFIG_PATH
          value: "/opt/custom-config.conf"
        - name: DB_DATABASE
          value: "africa"
        - name: DB_HOSTNAME
          value: "db-deafrica-eks-default.clgqttgwz3jw.us-west-2.rds.amazonaws.com"
        - name: DB_PORT
          value: "5432"
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: africa-datacube
              key: postgres-username
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: africa-datacube
              key: postgres-password

      