apiVersion: v1
kind: Pod
metadata:
  name: dev-pod
  namespace: processing
  labels:
    app: odc
  annotations:
    iam.amazonaws.com/role: deafrica-prod-eks-jhub
spec:
  containers:
  - name: datacube-indexer-dev
    image: opendatacube/datacube-index
    env:
    - name: DB_USERNAME
      valueFrom:
        secretKeyRef:
          name: ows-db
          key: postgres-username
    - name: DB_PASSWORD
      valueFrom:
        secretKeyRef:
          name: ows-db
          key: postgres-password
    - name: DB_DATABASE
      value: "africa"
    - name: DB_HOSTNAME
      value: "database-write.local"
    - name: AWS_DEFAULT_REGION
      value: us-west-2
    command: ["/bin/sh", "-ec", "while :; do echo '.'; sleep 5 ; done"]
