apiVersion: v1
kind: Pod
metadata:
  name: x3-c2-wofs-add-to-alchemist
  namespace: processing
  labels:
    app: x3-c2-wofs-add-to-alchemist
  annotations:
    iam.amazonaws.com/role: deafrica-ec2-s3_access
spec:
  containers:
  - name: x3-c2-wofs-add-to-alchemist
    image: opendatacube/datacube-alchemist
    #args: ["/usr/bin/env", "sleep", "10000"]
    #args: [ "datacube-alchemist", "addtoqueue" , "'time in 2018-12'"]
    args: [ "datacube-alchemist", "addtoqueue", "time in 2019 lon in range(39.5,39.7) lat in range(-4.2,-4.1)"]
    resources:
      requests:
        cpu: 1
        memory: 8192Mi
      limits:
        memory: 8192Mi
    tty: true
    stdin: true
    env:
    - name: ALCHEMIST_ADDTOQUEUE_LIMIT
      value: "2"
    - name: ALCHEMIST_ADDTOQUEUE_MESSAGE_QUEUE
      value: "alchemist-standard"
    - name: ALCHEMIST_ADDTOQUEUE_ENVIRONMENT
      value: "datacube"
    - name: ALCHEMIST_ADDTOQUEUE_CONFIG_FILE
      value: "https://raw.githubusercontent.com/digitalearthafrica/DEAfrica_scripts/master/alchemist_config/DEAfrica_wofs_c2_with_dsm_test.yaml"
    - name: DB_USERNAME
      valueFrom:
        secretKeyRef:
          name: ows-db
          key: postgres-username
    - name: DB_PASSWORD
      valueFrom:
        secretKeyRef:
          name: ows-db
          key: postgres-password
    - name: AWS_DEFAULT_REGION
      valueFrom:
        secretKeyRef:
          name: processing-aws-creds-dev
          key: AWS_DEFAULT_REGION
    - name: AWS_ACCESS_KEY_ID
      valueFrom:
        secretKeyRef:
          name: processing-aws-creds-dev
          key: AWS_ACCESS_KEY_ID
    - name: AWS_SECRET_ACCESS_KEY
      valueFrom:
        secretKeyRef:
          name: processing-aws-creds-dev
          key: AWS_CR
    - name: DB_DATABASE
      value: "collection2"
    - name: DB_HOSTNAME
      value: "database.local"
    - name: DB_PORT
      value: "5432"
    - name: LOG_LEVEL
      value: "DEBUG"
  nodeSelector:
    beta.kubernetes.io/os: linux
  restartPolicy: Never
